### ISSUE TITLE
handling macOS logs CoreBluetooth warning: delegate does not implement -[peripheral:didModifyServices:] when Android BitChat app exits

### ISSUE THREAD

**Issue by 1amhesus** [ShilohEye/bitchat-terminal#7]
### Description

When using **bitch@** on macOS(Ventura 13.1) and connecting to an Android device(version 12) running bitchat, the following CoreBluetooth warning appears when the Android app is closed:

`[CoreBluetooth] WARNING: The delegate for <CBPeripheral: ..., name = ..., state = connected> does not implement -[peripheral:didModifyServices:]`

<img width="1919" height="819" alt="Image" src="https://github.com/user-attachments/assets/39d835d0-ccdb-4840-81e0-9fc3e296faab" />

### Context

After successful pairing and connection between macOS **bitch@** and Android **bitchat** devices, the peripheral is still considered "connected" by CoreBluetooth when the Android app is closed(intentionally). 

As a result, CoreBluetooth detects that the GATT services have changed, and attempts to notify the delegate. However, the current **bitch@** implementation (via btleplug) does not implement didModifyServices:, leading to this warning in logs.

### Expected Behavior

Ideally, the delegate should implement didModifyServices: in order to:

- React to service changes (e.g., disconnection message, reconnection message)

- Maintain Bluetooth session robustness to prevent unnecessary warnings from CoreBluetooth

### Current Behavior

**bitch@** continues running normally functionality isn't broken, but the warning could cause confusion or obscure real errors during development.

### Discussion Point 1: Should we implement didModifyServices:?

→ Implementing didModifyServices: would suppress warnings and allow the app to detect or respond to GATT service changes more robustly.
(This method is not implemented in the current btleplug-based bitch@ client, and its absence leads to missed callbacks for service changes.)

### Discussion Point 2: What is the proper flow for automatic reconnection?

→ Automatic reconnection should rely on didDisconnectPeripheral or on_disconnect to scan and reconnect, rather than didModifyServices:.

### Additional Notes

I manually restarted the bitchat app on my Android device, which triggered a runtime error:  
`Runtime Error: Peer removed pairing information`

After unpairing the device from the Android system and reconnecting, the issue was resolved.

While the exact cause remains under investigation, it appears to be an edge case in how CoreBluetooth or btleplug re-identifies previously paired devices using peripheral UUIDs.

**Comment by ShilohEye** [comment]
Yeah a lot of the time "After unpairing the device from the Android system and reconnecting, the issue was resolved." this solves those issues  

My guess would be that this may be an issue on how Android handles graceful disconnects / leaves. Can you try with iOS as well and see if you get the same issue? Getting on macOS soon to see if debug logs look different but also try running with debug.

**Comment by 1amhesus** [comment]
Thanks for the suggestion! I’ll run the same test on the iOS simulator and share what I find — curious fingers ready for some iOS tinkering. 

Also, I’ve been wondering the same about how Android handles disconnects, so I’d like to dig a bit deeper during iOS debugging to see if we can pinpoint what’s really happening.

**Comment by 1amhesus** [comment]
I’ve been thinking and trying iOS as well to check if the same issue occurs with `-dd mode`. 

By the way, before diving into the Bluetooth-level issue of handling GATT service, I first encountered a few bugs at the application level. So I looked into the relevant code during runtime(I couldn't ignore the bugs!), and for now, I’ve documented the problems related to iOS key exchange and nickname decoding failure in #15(It seems this is due to the structure of the packet messages sent from iOS, and we’ll likely need to update the encryption module to handle key exchange properly according to that format).

getting back to the point,

`> 2025-08-03 20:42:05.870826+0900 bitchat[86773:3609705] [CoreBluetooth] WARNING: The delegate for <CBPeripheral: 0x600001e28000, identifier = 4418FD87-8213-016B-EA6A-BF3DC9C7ED28, name = iPhone, mtu = 527, state = connected> does not implement -[peripheral:didModifyServices:]`

like what we can see above( I used command (lldb) run -dd ), It seems that the same issue, and we may need to analyze proper handling based on GATT service structure.

Given that, if we want to revisit the logic for handling Bluetooth connections state changes—including GATT service updates, app shutdowns, and disconnections on macOS and other OS. For this work, I think the `-dd mode` has its limitations to improve this further. While -dd is currently useful for debugging handshakes, packet transmission, and key exchanges, it doesn’t surface system-level Bluetooth connection events. For now, using` log stream `is the most practical way to monitor those, but if needed, we may require a development environment that supports FFI-based or indirect monitoring of GATT service states, though implementing that would be a time-consuming task.

Anyways, I’ve realized that a graceful exit model is essential to ensure smooth reconnections. This also highlights the need to further enhance the `-dd mode` you developed.
